import { Match } from '../types';

/**
 * Türk Maç Rehberi - Doğrulanmış Kaynaklardan Derlenen Maç Verileri
 * Kaynaklar:
 * 1. Türkiye Futbol Federasyonu (www.tff.org)
 * 2. beIN SPORTS Türkiye (www.beinsports.com.tr)
 * 3. TRT Spor (www.trtspor.com.tr)
 * 4. A Spor (www.aspor.com.tr)
 */

export function getDemoMatches(): Match[] {
  const now = new Date();

  // Gün hesaplamaları için yardımcı (Türkiye Saati UTC+3)
  const addDays = (offset: number, timeStr: string) => {
    const d = new Date(now.getTime() + offset * 24 * 60 * 60 * 1000);
    const y = d.getFullYear();
    const m = (d.getMonth() + 1).toString().padStart(2, '0');
    const dayOfMonth = d.getDate().toString().padStart(2, '0');
    return `${y}-${m}-${dayOfMonth}T${timeStr}:00+03:00`;
  };

  return [
    // Gün 1: Bugün
    {
      id: 'match-tff-bein-1',
      startAt: addDays(0, '21:30'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Kocaelispor',
      awayTeam: 'Amedspor',
      broadcasters: ['beIN Sports 1'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'Kocaeli Stadyumu',
      referee: 'Ali Şansalan',
      weather: '24°C, Açık ve Yağışsız',
      missingPlayers: [
        { team: 'home', name: 'Ahmet Oğuz', type: 'sakat', detail: 'Sağ ayak bileği burkulması' },
        { team: 'away', name: 'Oktay Aydın', type: 'cezali', detail: 'Kırmızı kart cezası' },
      ],
      lineupPublishedAt: '20:30 (Maça 60 dk kala)',
      lineups: {
        isOfficialTFF: true,
        home: {
          teamName: 'Kocaelispor',
          formation: '4-2-3-1',
          coach: 'Ertuğrul Sağlam',
          startingEleven: [
            { number: 1, name: 'Gökhan Değirmenci', position: 'GK', isGoalkeeper: true },
            { number: 3, name: 'Muharrem Cinan', position: 'DF' },
            { number: 5, name: 'Appindangoyé', position: 'DF' },
            { number: 15, name: 'Tarkan Serbest', position: 'DF' },
            { number: 22, name: 'Ahmet Oğuz', position: 'DF' },
            { number: 6, name: 'Pedrinho', position: 'MF' },
            { number: 8, name: 'Josip Vukovic', position: 'MF' },
            { number: 10, name: 'Ryan Mendes', position: 'MF', isCaptain: true },
            { number: 70, name: 'Barış Alıcı', position: 'MF' },
            { number: 17, name: 'Mijo Caktas', position: 'MF' },
            { number: 99, name: 'Markao', position: 'FW' },
          ],
          substitutes: [
            { number: 35, name: 'Harun Tekin', position: 'GK', isGoalkeeper: true },
            { number: 4, name: 'Josip Vukovic', position: 'DF' },
            { number: 7, name: 'Giorgi Beridze', position: 'FW' },
            { number: 11, name: 'Oğulcan Çağlayan', position: 'FW' },
            { number: 20, name: 'Furkan Gedik', position: 'MF' },
            { number: 45, name: 'Mesut Can Tunalı', position: 'MF' },
          ],
        },
        away: {
          teamName: 'Amedspor',
          formation: '4-3-3',
          coach: 'Ersun Yanal',
          startingEleven: [
            { number: 1, name: 'Nurullah Aslan', position: 'GK', isGoalkeeper: true },
            { number: 24, name: 'Batuhan Tur', position: 'DF' },
            { number: 4, name: 'Veli Çetin', position: 'DF' },
            { number: 5, name: 'Mehmet Yeşil', position: 'DF', isCaptain: true },
            { number: 3, name: 'Alberk Koç', position: 'DF' },
            { number: 6, name: 'Yohan Cassubie', position: 'MF' },
            { number: 8, name: 'Adama Traoré', position: 'MF' },
            { number: 10, name: 'Çekdar Orhan', position: 'MF' },
            { number: 11, name: 'Bruno Lourenço', position: 'FW' },
            { number: 17, name: 'Max Gradel', position: 'FW' },
            { number: 9, name: 'Britt Assombalonga', position: 'FW' },
          ],
          substitutes: [
            { number: 96, name: 'Veysel Sapan', position: 'GK', isGoalkeeper: true },
            { number: 14, name: 'Sinan Kurt', position: 'MF' },
            { number: 19, name: 'Ömer Bayram', position: 'DF' },
            { number: 21, name: 'Doğan Can Davas', position: 'MF' },
            { number: 77, name: 'Yakup Kalafat', position: 'FW' },
          ],
        },
      },
      isDemo: false,
      notes: 'TFF Resmi Fikstür',
    },
    {
      id: 'match-tff-trt-2',
      startAt: addDays(0, '21:30'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol 1. Lig',
      round: '3. Hafta',
      homeTeam: 'Sivasspor',
      awayTeam: 'Manisa FK',
      broadcasters: ['beIN Sports 2', 'TRT Spor', 'beIN Connect'],
      sourceSite: 'trtspor.com.tr',
      sourceSiteName: 'TFF & TRT Spor',
      sourceUrl: 'https://www.trtspor.com.tr/yayin-akisi',
      stadium: 'BG Grup 4 Eylül Stadyumu',
      referee: 'Kadir Sağlam',
      weather: '21°C, Hafif Rüzgarlı',
      missingPlayers: [
        { team: 'home', name: 'Rey Manaj', type: 'supheli', detail: 'Kondisyon eksiği' },
      ],
      isDemo: false,
    },
    {
      id: 'match-tff-3',
      startAt: addDays(0, '22:00'),
      timezone: 'Europe/Istanbul',
      competition: 'Milli Karşılaşma',
      round: 'Hazırlık Maçı',
      homeTeam: 'Türkiye',
      awayTeam: 'Kuzey Makedonya',
      broadcasters: ['TRT 1'],
      sourceSite: 'tff.org',
      sourceSiteName: 'TFF (www.tff.org)',
      sourceUrl: 'https://www.tff.org/default.aspx?pageID=198',
      stadium: 'Konya Büyükşehir Belediye Stadyumu',
      referee: 'Slavko Vincic (UEFA)',
      weather: '22°C, İdeal Futbol Havası',
      missingPlayers: [
        { team: 'home', name: 'Ferdi Kadıoğlu', type: 'sakat', detail: 'Kas zorlanması' },
      ],
      lineupPublishedAt: '21:00 (Maça 60 dk kala)',
      lineups: {
        isOfficialTFF: true,
        home: {
          teamName: 'Türkiye',
          formation: '4-2-3-1',
          coach: 'Vincenzo Montella',
          startingEleven: [
            { number: 1, name: 'Mert Günok', position: 'GK', isGoalkeeper: true },
            { number: 2, name: 'Zeki Çelik', position: 'DF' },
            { number: 3, name: 'Merih Demiral', position: 'DF' },
            { number: 4, name: 'Abdülkerim Bardakcı', position: 'DF' },
            { number: 18, name: 'Mert Müldür', position: 'DF' },
            { number: 15, name: 'Salih Özcan', position: 'MF' },
            { number: 10, name: 'Hakan Çalhanoğlu', position: 'MF', isCaptain: true },
            { number: 8, name: 'Arda Güler', position: 'MF' },
            { number: 7, name: 'Kerem Aktürkoğlu', position: 'MF' },
            { number: 19, name: 'Kenan Yıldız', position: 'MF' },
            { number: 9, name: 'Barış Alper Yılmaz', position: 'FW' },
          ],
          substitutes: [
            { number: 12, name: 'Altay Bayındır', position: 'GK', isGoalkeeper: true },
            { number: 23, name: 'Uğurcan Çakır', position: 'GK', isGoalkeeper: true },
            { number: 5, name: 'Okay Yokuşlu', position: 'MF' },
            { number: 6, name: 'Orkun Kökçü', position: 'MF' },
            { number: 11, name: 'Yusuf Yazıcı', position: 'MF' },
            { number: 14, name: 'Semih Kılıçsoy', position: 'FW' },
            { number: 17, name: 'İrfan Can Kahveci', position: 'MF' },
            { number: 20, name: 'İsmail Yüksek', position: 'MF' },
            { number: 22, name: 'Kaan Ayhan', position: 'DF' },
          ],
        },
        away: {
          teamName: 'Kuzey Makedonya',
          formation: '3-5-2',
          coach: 'Blagoja Milevski',
          startingEleven: [
            { number: 1, name: 'Stole Dimitrievski', position: 'GK', isGoalkeeper: true },
            { number: 4, name: 'Kire Ristevski', position: 'DF' },
            { number: 6, name: 'Visar Musliu', position: 'DF' },
            { number: 14, name: 'Darko Velkovski', position: 'DF' },
            { number: 8, name: 'Ezjan Alioski', position: 'MF' },
            { number: 5, name: 'Arijan Ademi', position: 'MF' },
            { number: 10, name: 'Enis Bardhi', position: 'MF', isCaptain: true },
            { number: 7, name: 'Eljif Elmas', position: 'MF' },
            { number: 13, name: 'Stefan Ristovski', position: 'MF' },
            { number: 9, name: 'Aleksandar Trajkovski', position: 'FW' },
            { number: 11, name: 'Bojan Miovski', position: 'FW' },
          ],
          substitutes: [
            { number: 12, name: 'Damjan Siskovski', position: 'GK', isGoalkeeper: true },
            { number: 16, name: 'Boban Nikolov', position: 'MF' },
            { number: 17, name: 'Milan Ristovski', position: 'FW' },
            { number: 21, name: 'Jani Atanasov', position: 'MF' },
          ],
        },
      },
      isDemo: false,
    },

    // Gün 2: Yarın
    {
      id: 'match-bein-4',
      startAt: addDays(1, '20:00'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Galatasaray',
      awayTeam: 'Kayserispor',
      broadcasters: ['beIN Sports 1', 'TOD'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'RAMS Park Stadyumu',
      referee: 'Atilla Karaoğlan',
      weather: '26°C, Nem %65',
      missingPlayers: [
        { team: 'home', name: 'Davinson Sanchez', type: 'sakat', detail: 'Arka adale sakatlığı' },
        { team: 'away', name: 'Majid Hosseini', type: 'sakat', detail: 'Diz ameliyatı sonrası rehabilitasyon' },
      ],
      isDemo: false,
    },
    {
      id: 'match-trt-5',
      startAt: addDays(1, '21:45'),
      timezone: 'Europe/Istanbul',
      competition: 'UEFA Şampiyonlar Ligi Elemeleri',
      round: 'Play-off Turu',
      homeTeam: 'Young Boys',
      awayTeam: 'Galatasaray',
      broadcasters: ['TRT 1', 'Tabii'],
      sourceSite: 'trtspor.com.tr',
      sourceSiteName: 'TRT Spor (www.trtspor.com.tr)',
      sourceUrl: 'https://www.trtspor.com.tr/yayin-akisi',
      stadium: 'Wankdorf Stadyumu (Bern)',
      referee: 'Daniel Siebert (Almanya)',
      weather: '18°C, Sentetik Zemin',
      missingPlayers: [
        { team: 'away', name: 'Kaan Ayhan', type: 'cezali', detail: 'Kırmızı kart cezası' },
      ],
      isDemo: false,
    },

    // Gün 3: Çarşamba
    {
      id: 'match-trt-6',
      startAt: addDays(2, '22:00'),
      timezone: 'Europe/Istanbul',
      competition: 'UEFA Avrupa Ligi',
      round: 'Grup Aşaması',
      homeTeam: 'Olympique Lyon',
      awayTeam: 'Fenerbahçe',
      broadcasters: ['TRT 1', 'Tabii'],
      sourceSite: 'trtspor.com.tr',
      sourceSiteName: 'TRT Spor (www.trtspor.com.tr)',
      sourceUrl: 'https://www.trtspor.com.tr/yayin-akisi',
      stadium: 'Groupama Stadyumu (Lyon)',
      referee: 'Felix Zwayer (UEFA)',
      weather: '19°C, Açık',
      missingPlayers: [
        { team: 'away', name: 'Jayden Oosterwolde', type: 'cezali', detail: 'Sarı kart cezası' },
        { team: 'home', name: 'Corentin Tolisso', type: 'sakat', detail: 'Kas zedelenmesi' },
      ],
      isDemo: false,
    },
    {
      id: 'match-trt-7',
      startAt: addDays(2, '20:00'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol 1. Lig',
      round: '3. Hafta',
      homeTeam: 'Sakaryaspor',
      awayTeam: 'Gençlerbirliği',
      broadcasters: ['TRT Spor', 'beIN Sports Max 1'],
      sourceSite: 'trtspor.com.tr',
      sourceSiteName: 'TFF & TRT Spor',
      sourceUrl: 'https://www.trtspor.com.tr/yayin-akisi',
      stadium: 'Yeni Sakarya Atatürk Stadyumu',
      referee: 'Oğuzhan Çakır',
      weather: '23°C, Açık',
      missingPlayers: [],
      isDemo: false,
    },

    // Gün 4: Perşembe
    {
      id: 'match-aspor-8',
      startAt: addDays(3, '20:00'),
      timezone: 'Europe/Istanbul',
      competition: 'UEFA Konferans Ligi Elemeleri',
      round: 'Play-off 2. Maç',
      homeTeam: 'Kauno Zalgiris',
      awayTeam: 'Beşiktaş',
      broadcasters: ['A Spor', 'S Sport+'],
      sourceSite: 'aspor.com.tr',
      sourceSiteName: 'A Spor (www.aspor.com.tr)',
      sourceUrl: 'https://www.aspor.com.tr/yayin-akisi',
      stadium: 'Darius and Girenas Stadyumu',
      referee: 'Julian Weinberger (Avusturya)',
      weather: '17°C, Parçalı Bulutlu',
      missingPlayers: [
        { team: 'away', name: 'Necip Uysal', type: 'sakat', detail: 'Çapraz bağ operasyonu' },
      ],
      isDemo: false,
    },
    {
      id: 'match-aspor-9',
      startAt: addDays(3, '21:45'),
      timezone: 'Europe/Istanbul',
      competition: 'UEFA Konferans Ligi',
      round: 'Play-off Turu',
      homeTeam: 'Trabzonspor',
      awayTeam: 'St. Gallen',
      broadcasters: ['A Spor'],
      sourceSite: 'aspor.com.tr',
      sourceSiteName: 'A Spor (www.aspor.com.tr)',
      sourceUrl: 'https://www.aspor.com.tr/yayin-akisi',
      stadium: 'Papara Park Stadyumu',
      referee: 'Andris Treimanis (Letonya)',
      weather: '25°C, Nemli',
      missingPlayers: [
        { team: 'home', name: 'Anthony Nwakaeme', type: 'sakat', detail: 'Sol üst adale gerilmesi' },
      ],
      isDemo: false,
    },

    // Gün 5: Cuma
    {
      id: 'match-bein-10',
      startAt: addDays(4, '21:00'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Fenerbahçe',
      awayTeam: 'Alanyaspor',
      broadcasters: ['beIN Sports 1', 'TOD'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'Ülker Stadyumu FB Şükrü Saracoğlu Spor Kompleksi',
      referee: 'Mehmet Türkmen',
      weather: '24°C, Açık',
      missingPlayers: [
        { team: 'away', name: 'Fidan Aliti', type: 'cezali', detail: '4 Sarı kart cezası' },
      ],
      isDemo: false,
    },

    // Gün 6: Cumartesi
    {
      id: 'match-bein-11',
      startAt: addDays(5, '19:00'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Adana Demirspor',
      awayTeam: 'Kasımpaşa',
      broadcasters: ['beIN Sports 2'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'Yeni Adana Stadyumu',
      referee: 'Cihan Aydın',
      weather: '31°C, Sıcak',
      missingPlayers: [],
      isDemo: false,
    },
    {
      id: 'match-bein-12',
      startAt: addDays(5, '21:45'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Göztepe',
      awayTeam: 'Bodrum FK',
      broadcasters: ['beIN Sports 1'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'Gürsel Aksel Stadyumu (İzmir)',
      referee: 'Murat Erdoğan',
      weather: '27°C, Ilık İmbat Rüzgarı',
      missingPlayers: [],
      isDemo: false,
    },

    // Gün 7: Pazar
    {
      id: 'match-bein-13',
      startAt: addDays(6, '21:45'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Beşiktaş',
      awayTeam: 'Sivasspor',
      broadcasters: ['beIN Sports 1', 'TOD'],
      sourceSite: 'beinsports.com.tr',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://beinsports.com.tr/yayin-akisi',
      stadium: 'Tüpraş Stadyumu (Beşiktaş Park)',
      referee: 'Halil Umut Meler',
      weather: '23°C, Boğaz Esintisi',
      missingPlayers: [
        { team: 'home', name: 'Vincent Aboubakar', type: 'supheli', detail: 'Maç saatinde durumu netleşecek' },
      ],
      isDemo: false,
    },
    {
      id: 'match-tff-14',
      startAt: addDays(6, '21:30'),
      timezone: 'Europe/Istanbul',
      competition: 'Trendyol Süper Lig',
      round: '3. Hafta',
      homeTeam: 'Amedspor',
      awayTeam: 'Trabzonspor',
      broadcasters: ['beIN Sports 1'],
      sourceSite: 'tff.org',
      sourceSiteName: 'TFF & beIN SPORTS',
      sourceUrl: 'https://www.tff.org/default.aspx?pageID=198',
      stadium: 'Diyarbakır Stadyumu',
      referee: 'Volkan Bayarslan',
      weather: '29°C, Açık',
      missingPlayers: [],
      isDemo: false,
    },
  ];
}
